package sumaApp;


/**
* sumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Suma.idl
* martes 18 de abril de 2017 11H13' COT
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
