package sumaApp;


/**
* sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Suma.idl
* martes 18 de abril de 2017 11H13' COT
*/

public interface sumaOperations 
{
  int sumar (int primernumero, int segundonumero);
  void shutdown ();
} // interface sumaOperations
